### PR TITLE
fixing issue inactiveColor doesn't pass from list of tabs

### PR DESCRIPTION
**Pull request by abathz**
Hello there 👋🏻 

I just fixing inactiveColor issue, please take a look, thanks!

### CODE REVIEW

**Comment by junhoyeo** [comment]
Thanks for the fix, @abathz!! 😚
I'll deploy the new version right now. Plus I promise to enhance this module more when given some free time! 🙏

**Comment by abathz** [comment]
Thank you very much @junhoyeo!! 🙏🏻

**Comment by abathz** [comment]
> Thanks for the fix, @abathz!! 😚
> I'll deploy the new version right now. Plus I promise to enhance this module more when given some free time! 🙏

@junhoyeo have you deploy the new version yesterday? because i haven't got new version this morning

**Comment by junhoyeo** [comment]
> > Thanks for the fix, @abathz!! 😚
> > I'll deploy the new version right now. Plus I promise to enhance this module more when given some free time! 🙏
> 
> @junhoyeo have you deploy the new version yesterday? because i haven't got new version this morning

Sorry I forgot that 😰 I bumped now-0.0.10 !! 
https://www.npmjs.com/package/react-native-bubble-tabbar

**Comment by abathz** [comment]
@junhoyeo Hello again! 👋🏻 can you build the library again? i cannot import with v0.0.10
Thanks!!🙏

**Pull request merged**
